# Julia for Travis: http://docs.travis-ci.com/user/languages/julia/

language: julia
julia:
  - 1.0
  - 1.1
  - 1.2

jobs:
  include:
    - stage: "Documentation"
      script:
        - julia --project -e 'using Pkg; Pkg.instantiate()'
        - julia --project -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.23.2"); Pkg.add(ps); Pkg.pin(ps)'
        - julia --project docs/make.jl
