# Julia for Travis: http://docs.travis-ci.com/user/languages/julia/

language: julia
julia:
  - 1.0
  - 1.1
  - 1.2

jobs:
  include:
    - stage: Documentation
      julia: 1.2
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y graphviz pdf2svg
        - sudo apt-get install -y texlive-latex-base texlive-binaries texlive-pictures texlive-latex-extra
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs --color=yes docs/make.jl
